### ISSUE TITLE
Help needed with evaluating oderatelaws() using  build_function() 

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/ModelingToolkit.jl#634] opened 2020-11-01 19:48 UTC
Hi,
I wanted some help in evaluating a vector of ```ModelingToolkit.oderatelaw``` from the time evolution of state variables in chemical reactions . Some discussion with @isaacsas  [here](https://github.com/SciML/Catalyst.jl/issues/269#issuecomment-719962060) has encouraged me to look into `build_function`, but with little success. Some of my attempts are listed there.
Any more direction or help is much appreciated.

**Comment by isaacsas** [comment] 2020-11-01 20:02
@shashi the issue is dropping `A(t)` to `A`. Should that be handled automatically in MT >= 4.0?

**Comment by isaacsas** [comment] 2020-11-02 20:32
Closed as being discussed in https://github.com/SciML/Catalyst.jl/issues/269.

**Comment by isaacsas** [comment] 2020-11-04 20:34
@shashi @YingboMa  This example from the linked Catalyst issue doesn't work due to lack of substitution for terms like `x1(t)` with corresponding `Sym`s as done here:
https://github.com/SciML/ModelingToolkit.jl/blob/1f35567f8c86b013798579bad7efb93a8cf53de0/src/systems/diffeqs/abstractodesystem.jl#L71-L80
Is this something that could be handled directly in `build_function` or with a preprocessing call? I think it is confusing to users that this wouldn't work.
```julia
@variables t x1(t) x2(t) k1 k2;
 a = [k1*x1^2, k2*x2];
f = build_function(a,[x1 ,x2, k1, k2]);
myfunc = eval(f[2]);
out_f = zeros(2);
myfunc(out, [1,1.0,2.0,1.0])
```
Note, this still fails if one instead uses
```julia
f = build_function(a,[x1 ,x2], [k1, k2], t)
```
for the function form.

Is the idea that @yewalenikhil65 should be doing something like
```julia
f = build_function(a,[x1 ,x2, k1, k2], conv=MT.states_to_sym([x1,x2,k1,k2]))
```
instead? If so it might be good to document this and add to one of the tutorials in the docs.

**Comment by shashi** [comment] 2020-11-05 17:58
Okay I believe we should make it just work without the extra step. Let me see if I can quickly make a PR for this.

**Closed** 2020-11-06 04:51 UTC
