### ISSUE TITLE
how to model a switch, I can not see what is wrong with my switch code.

### ISSUE THREAD

**Issue by yanshuchang** [SciML/ModelingToolkit.jl#1978] opened 2022-11-28 22:31 UTC
``` Julia

function switch(;name, m)
   
   @named  oneport = OnePort()
   
   @unpack v, i = oneport
   
   eqs = [
            i ~ ifelse((m > 0),  i,  0),
           # v ~ ifelse((m > 0),  v,  v),
             
           ]

   extend(ODESystem(eqs, t, [], []; name = name), oneport)
   
end



function igbt(;name, m)    

   @named   p   =  Pin()
   @named   n   =  Pin()
   
   @named         sw   =  switch(m = m)
   @named          l   =  Inductor(L = 1) 
   @named          r   =  Resistor(R = 4) 

       eqs = [
       
       # 连接属性
        connect(p, sw.p)

        connect(sw.n, r.p)
       
        connect(r.n, n)

       ]

       # compose(ODESystem(eqs, t, [], []; name = name), [p, n, lm, rm])

   return  compose(ODESystem(eqs, t, [], []; name = name), [p, n,  sw, r])

end


@named     igbt1 =   igbt(m = 3)
@named input_v   = ModelingToolkitStandardLibrary.Blocks.Constant(k=4)
@named input_pin = ModelingToolkitStandardLibrary.Electrical.Voltage()
@named         g = Ground()


structural_simplify(igbt1)

eqs = [
   connect(input_pin.V, input_v.output)
   
   connect(input_pin.p, igbt1.p)
   connect(igbt1.n, input_pin.n)

   connect(input_pin.n, g.g)
]

@named _rrr  =   ODESystem(eqs, t)
@named  rrr  =   compose(_rrr, [input_v, input_pin, igbt1,  g])
model = structural_simplify(rrr)

prob = ODEProblem(model, [ ], (0., 10.))
sol = solve(prob)
plot(sol(0:0.1:100, idxs = igbt1.n.i))

```

**Comment by yanshuchang** [comment] 2022-11-28 22:31
who can help to solve this problem ?!!!!!!

**Comment by YingboMa** [comment] 2022-11-28 22:52
Duplicate of #1977

**Closed by YingboMa** 2022-11-28 22:52 UTC
