### ISSUE TITLE
WARNING: importing deprecated binding Symbolics.@register into ModelingToolkit.

### ISSUE THREAD

**Issue by prbzrg** [SciML/ModelingToolkit.jl#2197] opened 2023-06-17 01:41 UTC
I got this warning in the precompilation:

```julia
┌ ModelingToolkit [961ee093-0014-501f-94e3-6117800e7a78]
│  WARNING: importing deprecated binding Symbolics.@register into ModelingToolkit.
└  
```

**Comment by ChrisRackauckas** [comment] 2023-06-17 14:05
@YingboMa do you know the cause of this one? I looked for `@register` in this repo and didn't find it.

**Comment by prbzrg** [comment] 2023-06-17 14:24
If you need the versions, the warning comes from:
https://github.com/impICNF/ContinuousNormalizingFlows.jl/actions/runs/5296322153/jobs/9587352257#step:6:784

**Comment by ChrisRackauckas** [comment] 2024-02-22 13:41
@ArnoStrouwen close this when we solve it.

**Comment by ArnoStrouwen** [comment] 2024-02-26 05:18
Should be good now.
I don't have close rights.

**Closed** 2024-02-26 06:09 UTC
