### ISSUE TITLE
Equality and inequality constraints are silently ignored

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1579] opened 2022-05-16 20:23 UTC
https://github.com/SciML/ModelingToolkit.jl/blob/5df79912e701c5a4c6b2c7e6022a2cb9448a8fdb/src/systems/optimization/optimizationsystem.jl#L185

The docs should mention this.

**Comment by lamorton** [comment] 2022-08-27 17:08
Duplicate of #1134 .

**Comment by ValentinKaisermayer** [comment] 2022-08-27 19:36
Fixed by #1660

**Closed** 2022-08-27 19:36 UTC
