### ISSUE TITLE
structural_simplify cannot detect variables depending on Differentials

### ISSUE THREAD

**Issue by CodeLenz** [SciML/ModelingToolkit.jl#1003] opened 2021-05-05 15:45 UTC
Given  a simple mass-spring-damper problem

> m D2(x) + c D(x) + k x  = f(t)

Now suppose I want to keep track of the damping force. I can try

```
 @parameters t k m ζ
 @variables x(t) F(t) FD(t)
 D = Differential(t)
 D2 = D*D
 f(t) = 100.0/m
 eq = [ F ~ f(t)/m,
           FD ~ ( ζ*2*sqrt(k*m)*D(x) )/m,
           D2(x) ~ F - (k/m)*x - FD  
]
 sys = ODESystem(eq,t)
 sys_simplified = structural_simplify(sys)
 sys_lower = ode_order_lowering(sys_simplified);

```
but when I try to use this approach I get 

```
prob = ODEProblem(sys_lower,u0,tspan,p,jac=true);
ArgumentError: Any[FD(t)] are missing from the variable map.
```

I read the documentation and it says that MTK can miss some variables in the mapping, and the suggestion is to use 
> ODESystem(eq,t).

It is not working in this case, so I suspect it is something related to the presence of D(x) in FD, since if I try to do the same thing with (k/m)*x it just works.

The complete code to obtain the error is 

```
using LinearAlgebra, Symbolics, ModelingToolkit, 
using DifferentialEquations

 @parameters t k m ζ
 @variables x(t) F(t) FS(t) FD(t)
 D = Differential(t)
D2 = D*D
f(t) = 100.0/m
eq = [ F ~ f(t)/m,
         FD ~ ( ζ*2*sqrt(k*m)*D(x) )/m,
         D2(x) ~ F -(k/m)*x - FD  
       ]
 sys = ODESystem(eq,t)
 sys_simplified = structural_simplify(sys)
 sys_lower = ode_order_lowering(sys_simplified)
 u0 = [D(x) => 0.0 , 
         x  => 1.0 ,
       ]
 p = [ k => 10.0,
       m => 1.0,
       ζ => 0.1
       ]
 tspan = (0.0, 10.0)
 prob = ODEProblem(sys_lower,u0,tspan,p)
 sol = solve(prob)

```

**Comment by ChrisRackauckas** [comment] 2021-05-06 12:54
Yes, this is just the "Differential on the RHS" issue.

**Comment by bradcarman** [comment] 2021-05-06 14:11
I was just about to post about this issue.  I have an example that eliminates a key equation and gives the wrong result.  The last equation is what drives the system, but is eliminated when using `dae_index_lowering` or `structural_simplify`

Here is the example

```julia
using ModelingToolkit
using DifferentialEquations

@parameters kp ki kd m k d
@variables t y(t) e(t) de(t) dde(t) x(t) dx(t) ddx(t)
D = Differential(t)


eqs = [
    D(y) ~ kp*de + ki*e + kd*dde
    D(e) ~ de
    D(de) ~ dde
    D(x) ~ dx
    D(dx) ~ ddx
    y ~ m*ddx + d*dx  + k*x 
    e ~ t - x 
    ]

defs = [y=>0, e=>0, de=>0, dde=>0, x=>0, dx=>0, ddx=>0, kp=>1, ki=>1, kd=>1, m=>1, d=>1, k=>1]
params = [kp, ki, kd, m, d, k]
sys = ODESystem(eqs,t,[y, e, de, x, dx, dde, ddx], params, defaults=defs)

test1 = alias_elimination(sys)
prob = ODEProblem(test1, [], (0, 3), [], tgrad=true, jac=true)
sol1 = solve(prob, ImplicitEuler(), adaptive=false, dt=1e-4)

test2 = structural_simplify(sys)
prob = ODEProblem(test2, [], (0, 3), [], tgrad=true) #adding jac=true causes hard crash of Julia
sol2 = solve(prob, ImplicitEuler(), adaptive=false, dt=1e-4)

test3 = structural_simplify(dae_index_lowering(sys))
prob = ODEProblem(test3, [], (0, 3), [], tgrad=true) #adding jac=true causes hard crash of Julia
sol3 = solve(prob, ImplicitEuler(), adaptive=false, dt=1e-4)
```
Both `sol2` and `sol3` return only zeros, which is not the correct answer to the problem.

![image](https://user-images.githubusercontent.com/40798837/117312737-4b133280-ae53-11eb-88fa-4a03a55c7165.png)

**Comment by ChrisRackauckas** [comment] 2021-05-06 14:14
This has nothing to do with this issue. But also, I can't parse what you're trying to do because you didn't include your analysis code.

**Comment by bradcarman** [comment] 2021-05-06 14:39
Maybe I should open a separate issue...please advise

The analysis code is simply the following (plotting `x` from `sol1` and `sol2`)...

```julia
using PlotlyJS
s = GenericTrace[]
push!(s, scatter(y=(0:1e-4:3), name="target"))
push!(s, scatter(y=sol1[x], name="alias_elimination"))
push!(s, scatter(y=sol2[x], name="structural_simplify"))
plot(s, Layout(yaxis_title="x [m]"))
```

The target is simply `t`

The meaning of the problem is I have an equation `e = t - x` which means the error sent to the controller is equal to the difference in setpoint (time) and position of a mass `x`.  The controller is represented by the first equation `D(y) ~ kp*de + ki*e + kd*dde` which outputs `y`.  The output `y` drives the mass, spring, damper system in the equation `y ~ m*ddx + d*dx  + k*x`

This problem doesn't need the `structural_simplify` equation, no equations should be eliminated, but it simply demonstrates a bug that equations are eliminated that shouldn't be.

**Comment by ChrisRackauckas** [comment] 2021-05-06 14:41
Open a separate issue

**Comment by CodeLenz** [comment] 2021-05-07 11:13
> Yes, this is just the "Differential on the RHS" issue.

Is there any workaround?

**Comment by YingboMa** [comment] 2021-05-07 21:42
Closing because this is a duplicate issue.

> Is there any workaround?

Define `D(x) ~ dx` and only have one differential on the LHS and no differential on the RHS.

**Closed by YingboMa** 2021-05-07 21:42 UTC
