### ISSUE TITLE
Simple model apparently runs out of memory

### ISSUE THREAD

**Issue by sh2pro** [SciML/ModelingToolkit.jl#2053] opened 2023-01-26 19:07 UTC
Please see https://github.com/JuliaLang/julia/issues/48418

The machine is an ml.m5.large AWS instance with 8GB of memory.
Should be more than enough for a model with a couple of dozens equations

**Comment by ChrisRackauckas** [comment] 2023-01-26 19:13
Closing since this is almost certainly a Base issue with parallel precompilation.

**Comment by sh2pro** [comment] 2023-01-26 19:14
can you explain? what is the workaround?

**Comment by ChrisRackauckas** [comment] 2023-01-26 19:20
Open Julia with less threads and see if that fixes it.

**Comment by sh2pro** [comment] 2023-01-27 07:24
It doesn't


```
(base) jovyan@julia-ml-m5-large:~/work$ julia --threads=1 test.jl
  Activating project at `~/work`
after using
here we go
Killed
(base) jovyan@julia-ml-m5-large:~/work$
```

**Comment by baggepinnen** [comment] 2023-01-27 08:24
I had problems about a week ago where all CI runs using MTK failed to precompile due to running out of memory. It has gone away by now, so maybe it will for you as well if you update all packages?

**Comment by sh2pro** [comment] 2023-01-27 08:35
Seems that `ODAEProblem()` is running out of memory, so I don't think it's related to precompilation

**Comment by ChrisRackauckas** [comment] 2023-01-27 08:37
Sounds like it's a core dump related to codegen then. Can you share the core dump? Write it to a file before the terminal crashes?

**Comment by ChrisRackauckas** [comment] 2023-01-27 10:52
What's the reproducible example? I ran the code and get that `Segment is not defined` at `@named s = S()`, and indeed `Segment` is not defined in this example and not in mtkstdlib.

**Comment by ChrisRackauckas** [comment] 2023-01-29 23:14
@YingboMa able to recreate at all?

**Comment by sh2pro** [comment] 2023-01-30 06:13
FYI, here's the environment:
```shell
(base) jovyan@julia-ml-t3-medium:~/work$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.5 (2023-01-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.8) pkg> activate .
  Activating project at `~/work`

(work) pkg> st
Status `~/work/Project.toml`
  [1b08a953] Dash v1.1.2
  [0c46a032] DifferentialEquations v7.6.0
  [c601a237] Interact v0.10.5
  [2fda8390] LsqFit v0.13.0
  [961ee093] ModelingToolkit v8.43.0
  [16a59e39] ModelingToolkitStandardLibrary v1.10.0
  [f0f68f2c] PlotlyJS v0.18.10
  [91a5bcdd] Plots v1.38.3
  [1986cc42] Unitful v1.12.2

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 2 virtual cores
Environment:
  JULIA_PKGDIR = /opt/julia
  JULIA_VERSION = 1.8.5
  JULIA_DEPOT_PATH = /opt/julia
```

On a Mac (Apple Silicon), I could see the Julia process allocate more than 50GB before I killed the process (didn't wait for the machine to crash)

**Comment by ChrisRackauckas** [comment] 2023-01-30 10:45
Is this isolated then to https://github.com/SciML/OrdinaryDiffEq.jl/issues/1857 and this should be closed? It would make sense if this was the RecursiveFactorization issue mentioned there. I don't see how ModelingToolkit could be the cause, but something weird in LoopVectorization/SIMD codegen at least sounds plausible.

**Comment by sh2pro** [comment] 2023-01-30 11:23
@ChrisRackauckas, unfortunately, even after starting from scratch, the same issue remains:

```shell
(base) jovyan@julia-ml-m5-large:~/work$ julia test.jl 
  Activating project at `~/work`
after using
here we go
Killed
(base) jovyan@julia-ml-m5-large:~/work$ julia

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.5 (2023-01-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.8) pkg> activate .
  Activating project at `~/work`

(work) pkg> st
Status `~/work/Project.toml`
  [0c46a032] DifferentialEquations v7.6.0
  [961ee093] ModelingToolkit v8.43.0
  [16a59e39] ModelingToolkitStandardLibrary v1.10.0
  [f0f68f2c] PlotlyJS v0.18.10
  [91a5bcdd] Plots v1.38.3
  [1986cc42] Unitful v1.12.2

julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 2 virtual cores
Environment:
  JULIA_PKGDIR = /opt/julia
  JULIA_VERSION = 1.8.5
  JULIA_DEPOT_PATH = /opt/julia

julia>
```

**Comment by ChrisRackauckas** [comment] 2023-01-30 11:26
And just to make sure, can you respond to this point?

> You're sure you are using a binary from https://julialang.org/downloads/? Your set of issues sound exactly like the kind of issues you'd get from Arch Linux's package manager where it purposefully uses the wrong LLVM version (for god knows what reason) which then makes a lot of code not work (because it's using the wrong version of the compiler tools).

Also to be sure, this is Apple Silicon (M1) on Linux?

**Comment by ChrisRackauckas** [comment] 2023-01-30 11:34
Okay yeah with your latest example I can reproduce. I get:

```
ERROR: OutOfMemoryError()
Stacktrace:
  [1] Array
    @ .\boot.jl:459 [inlined]
  [2] Array
    @ .\boot.jl:468 [inlined]
  [3] similar
    @ .\array.jl:378 [inlined]
  [4] similar
    @ .\abstractarray.jl:797 [inlined]
  [5] _typed_vcat_similar
    @ .\abstractarray.jl:1571 [inlined]
  [6] _typed_vcat(#unused#::Type{Int64}, V::Vector{Vector{Int64}})
    @ Base .\abstractarray.jl:1572
  [7] reduce(#unused#::typeof(vcat), A::Vector{Vector{Int64}})
    @ Base .\abstractarray.jl:1650
  [8] gen_nlsolve!(is_not_prepended_assignment::BitVector, eqs::SubArray{Equation, 1, Vector{Equation}, Tuple{Vector{Int64}}, false}, vars::SubArray{Any, 1, Vector{Any}, Tuple{Vector{Int64}}, false}, u0map::Dict{Any, Any}, assignments::Vector{SymbolicUtils.Code.Assignment}, ::Tuple{Vector{Vector{Int64}}, Vector{BitSet}}, var2assignment::Dict{Any, Int64}; checkbounds::Bool)
    @ ModelingToolkit.StructuralTransformations C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:117
  [9] build_torn_function(sys::ODESystem; expression::Bool, jacobian_sparsity::Bool, checkbounds::Bool, max_inlining_size::Nothing, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ModelingToolkit.StructuralTransformations C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:277       
 [10] build_torn_function
    @ C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:228 [inlined]
 [11] ODAEProblem{true}(sys::ODESystem, u0map::Vector{Pair}, tspan::Tuple{Int64, Int64}, parammap::SciMLBase.NullParameters; callback::Nothing, use_union::Bool, check::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ModelingToolkit.StructuralTransformations C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:535       
 [12] ODAEProblem (repeats 2 times)
    @ C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:525 [inlined]
 [13] ODAEProblem(::ODESystem, ::Vararg{Any}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ ModelingToolkit.StructuralTransformations C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:523       
 [14] ODAEProblem(::ODESystem, ::Vararg{Any})
    @ ModelingToolkit.StructuralTransformations C:\Users\accou\.julia\packages\ModelingToolkit\egI3v\src\structural_transformation\codegen.jl:523       
 [15] top-level scope
    @ c:\Users\accou\OneDrive\Computer\Desktop\test.jl:105
```

it seems to hit some bad spot of codegen. @YingboMa it seems like a good example to dig into.

**Comment by sh2pro** [comment] 2023-01-30 11:38
> And just to make sure, can you respond to this point?
> 
> > You're sure you are using a binary from https://julialang.org/downloads/? Your set of issues sound exactly like the kind of issues you'd get from Arch Linux's package manager where it purposefully uses the wrong LLVM version (for god knows what reason) which then makes a lot of code not work (because it's using the wrong version of the compiler tools).

Yes, I'm using the docker image from https://github.com/jupyter/docker-stacks/tree/main/datascience-notebook which downloads Julia directly from https://julialang-s3.julialang.org/.

Note that the same problem occurs with a `juliaup` installed Julia 1.8.5 on an *Apple Silicon* (ARM64) Mac.

**Comment by ChrisRackauckas** [comment] 2023-01-30 11:39
Yes, it seems to be some cycle in the structural simplify logic.

**Closed** 2023-02-06 16:14 UTC
