### ISSUE TITLE
Cannot use structural parameter as array size

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#2704] opened 2024-05-06 09:10 UTC
```julia
@mtkmodel Foo begin
    @structural_parameters begin
        nx = 2
    end
    @variables begin
        (x(t)[1:nx]), [description = "State"]
    end
    @equations begin
    end
end
```
```
ERROR: promotion of types Int64 and Symbol failed to change any arguments
```

With explicit array size, it works
```julia
julia> @mtkmodel Foo begin
           @structural_parameters begin
               nx = 2
           end
           @variables begin
               (x(t)[1:2]), [description = "State"]
           end
           @equations begin
           end
       end
ModelingToolkit.Model{typeof(__Foo__), Dict{Symbol, Any}}(__Foo__, Dict{Symbol, Any}(:variables => Dict{Symbol, Dict{Symbol, Any}}(:x => Dict(:type => Real, :description => "State", :size => (2,))), :kwargs => Dict{Symbol, Dict}(:nx => Dict(:value => 2), :x => Dict{Symbol, Union{Nothing, UnionAll}}(:value => nothing, :type => AbstractArray{Real})), :structural_parameters => Dict{Symbol, Dict}(:nx => Dict(:value => 2)), :independent_variable => t, :equations => Any[]), false)
```

**Comment by jaakkor2** [comment] 2024-05-07 11:16
Duplicate of https://github.com/SciML/ModelingToolkit.jl/issues/2453?

**Comment by dfabianus** [comment] 2024-06-15 13:55
Is there a workaround to allow variable sized arrays?

**Comment by ChrisRackauckas** [comment] 2024-06-15 16:21
For what? That seems very orthogonal to this issue.

**Comment by ven-k** [comment] 2024-10-15 17:54
With https://github.com/SciML/ModelingToolkit.jl/pull/3107, this is now possible

**Closed** 2024-10-15 18:09 UTC
Labels: bug, usability
