### ISSUE TITLE
Problem with inversion of symbolic matrices

### ISSUE THREAD

**Issue by dcabecinhas** [SciML/ModelingToolkit.jl#458] opened 2020-06-16 13:29 UTC
Inverting a matrix with symbolic entries leads to appearance of weird booleans on the final expression. Steps to reproduce:

```
using ModelingToolkit
@variables M[1:2,1:2]
inv(M)
```

It seems to be related with this specific step of inverse computation:

```
  In inv!(A) at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/lu.jl:477
  >477  inv!(A::LU{T,<:StridedMatrix}) where {T} =
  478      ldiv!(A.factors, copy(A), Matrix{T}(I, size(A, 1), size(A, 1)))
```
The LU factorization happens without troubles but the `Matrix{T}(I, size(A, 1), size(A, 1))` constructor introduces the booleans. See the following excerpt of a debugging trace:
```
  In inv(A) at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:762
  766          Ai = triu!(parent(inv(UpperTriangular(AA))))
  767      elseif istril(AA)
  768          Ai = tril!(parent(inv(LowerTriangular(AA))))
  769      else
  >770          Ai = inv!(lu(AA))
  771          Ai = convert(typeof(parent(Ai)), Ai)
  772      end
  773      return Ai
  774  end

  About to run: <(LinearAlgebra.inv!)(LU{Operation,Array{Operation,2}}(Operation[M₁ˏ₁ M₁ˏ₂; M₂ˏ₁ * inv(...>
  1|debug> s
  failed to highlight code, Base.InvalidCharError{Char}('\xe2')
  In inv!(A) at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/lu.jl:477
  >477  inv!(A::LU{T,<:StridedMatrix}) where {T} =
  478      ldiv!(A.factors, copy(A), Matrix{T}(I, size(A, 1), size(A, 1)))

  1|julia> Matrix{T}(I, size(A, 1), size(A, 1))
  2×2 Array{Operation,2}:
  identity(true)     identity(0)
      identity(0)  identity(true)

  1|julia> A
  LU{Operation,Array{Operation,2}}
  L factor:
  2×2 Array{Operation,2}:
        identity(1)  identity(0)
  M₂ˏ₁ * inv(M₁ˏ₁)  identity(1)
  U factor:
  2×2 Array{Operation,2}:
          M₁ˏ₁                              M₁ˏ₂
  identity(0)  M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂

```

**Comment by ChrisRackauckas** [comment] 2020-06-16 14:04
This is fixed on the latest release.

**Comment by dcabecinhas** [comment] 2020-06-16 14:18
Doesn't look like. Maybe on `master` but not on v3.10.2 (latest according to https://github.com/SciML/ModelingToolkit.jl/releases ).
```

julia> using Pkg; Pkg.API.status("ModelingToolkit")
Status `~/.julia/environments/v1.4/Project.toml`
  [961ee093] ModelingToolkit v3.10.2

julia> @variables M[1:2,1:2]
(Operation[M₁ˏ₁ M₁ˏ₂; M₂ˏ₁ M₂ˏ₂],)

julia> inv(M)
2×2 Array{Operation,2}:
 M₁ˏ₁ \ (identity(true) - M₁ˏ₂ * ((M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(0) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(true))))  …  M₁ˏ₁ \ (identity(0) - M₁ˏ₂ * ((M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(true) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(0))))
                                    (M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(0) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(true))                                     (M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(true) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(0))


```

**Comment by ChrisRackauckas** [comment] 2020-06-16 14:22
https://github.com/SciML/ModelingToolkit.jl/pull/455 fixed it, so it should be in the v3.10.2 release (which was only released a few hours ago, so your first test was probably on v3.10.1)

**Comment by dcabecinhas** [comment] 2020-06-16 14:42
Can I ask you to double check with 

```
using ModelingToolkit
@variables M[1:2,1:2]
inv(M)
```

please? I updated my installation, double-checked the version number (`[961ee093] ModelingToolkit v3.10.2` on my upper post) and looking at the sourcecode I see your latest PR changes.
But the resulting inverse still has `identity(true)`...

**Comment by ChrisRackauckas** [comment] 2020-06-16 14:44
```julia
julia> using ModelingToolkit

julia> @variables M[1:2,1:2]
(Operation[M₁ˏ₁ M₁ˏ₂; M₂ˏ₁ M₂ˏ₂],)

julia> inv(M)
2×2 Array{Operation,2}:
 M₁ˏ₁ \ (identity(true) - M₁ˏ₂ * ((M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(0) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(true))))  …  M₁ˏ₁ \ (identity(0) - M₁ˏ₂ * ((M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(true) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(0))))
                                    (M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(0) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(true))                                     (M₂ˏ₂ - (M₂ˏ₁ * inv(M₁ˏ₁)) * M₁ˏ₂) \ (identity(true) - (M₂ˏ₁ * inv(M₁ˏ₁)) * identity(0))
```

I'll see where that identity(true) is coming from.

**Comment by ChrisRackauckas** [comment] 2020-06-16 14:45
Oh wait, the issue isn't about the inversion?

**Comment by dcabecinhas** [comment] 2020-06-16 14:50
This arises during the inversion. The inversion itself seems ok (replacing true by '1') but something is messing up the types. I'm not sure how problematic this is but doesn't seem right.

I kind of pinpointed it to that `Matrix{T}(I, size(A, 1), size(A, 1))` but your (the package developers) would know better.

**Comment by ChrisRackauckas** [comment] 2020-06-16 15:12
I'm not sure what an issue is. `identity(0)` is the way to represent `Constant(0)` as an `Operation`.

**Comment by ChrisRackauckas** [comment] 2020-06-16 15:23
Closing because it's not clear there's an issue here: `identity(0)` is just a correct operation

**Closed by ChrisRackauckas** 2020-06-16 15:23 UTC
