### ISSUE TITLE
Handle delays in ODESystem

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#1800] opened 2022-09-01 15:31 UTC
https://gist.github.com/YingboMa/667c4420cfec9e050188eee3a5285e6f

**Comment by ChrisRackauckas** [comment] 2022-09-08 09:03
Duplicate of https://github.com/SciML/ModelingToolkit.jl/issues/955

**Closed by ChrisRackauckas** 2022-09-08 09:03 UTC
