### ISSUE TITLE
Simulation fails when using parameters in the initial value map

### ISSUE THREAD

**Issue by JKRT** [SciML/ModelingToolkit.jl#991] opened 2021-04-29 09:33 UTC
Hi, 

Version:
[961ee093] ModelingToolkit v5.16.0

I have the following Lotka Volterra model:
```
#= Lotka-Volterra, John Tinnerholm=#
using ModelingToolkit    
using DiffEqBase    
using DifferentialEquations    
function LotkaVolterraSimulate(tspan = (0.0, 100.0))                
  pars = @parameters(begin             
                     alpha
                     x0
                     gamma
                     y0
                     delta
                     beta            
                     t
                     end)        
  vars = @variables(begin             
                    y(t)
                    x(t)                    
                    end)        
  der = Differential(t)        
  eqs = [der(y) ~ (delta * x - gamma) * y, der(x) ~ (alpha - beta * y) * x]        
  nonLinearSystem =
    ODESystem(eqs, t, vars, pars, name = :($(Symbol("LotkaVolterra"))))        
  pars = [
    alpha => 0.1,
    x0 => 10.0,
    gamma => 0.4,
    y0 => 10.0,
    delta => 0.02,
    beta => 0.02,
    t => tspan[1],
  ]        
  initialValues = [
    y => 10.0,
    x => 10.0
  ]        
  firstOrderSystem = ModelingToolkit.ode_order_lowering(nonLinearSystem)        
  reducedSystem = dae_index_lowering(firstOrderSystem)        
  problem = ODEProblem(reducedSystem, initialValues, tspan, pars)
  return problem
end
```

This works and simulates just fine! 
![image](https://user-images.githubusercontent.com/8775827/116530043-de8db600-a8dd-11eb-925c-a75f0be824f7.png)

However, if I use the parameters for the initial values that is 
```
  initialValues = [
    y => x0,
    x => y0
  ]        
```
and running it with:

`sol = solve(LotkaVolterraSimulate(), Tsit5())
`
I get the following error: 

```
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] recursive_unitless_bottom_eltype(a::Type{Any}) (repeats 79984 times)
   @ RecursiveArrayTools ~\.julia\packages\RecursiveArrayTools\K3lTR\src\utils.jl:86
in expression starting at C:<Path>\LotkaVolterra.jl:40
```

Is this intended or a bug? 

Cheers,
John

**Comment by ChrisRackauckas** [comment] 2021-04-29 10:24
Not intended and a good simple example, thanks. For some reason `u0` comes out as type `Vector{Any}`, fixing inferene would fix this.

**Comment by wsphillips** [comment] 2021-05-17 19:59
I hit the same issue when passing a map of defaults to `ODESystem` that includes initial state values defined by a `Term` that should be resolvable (i.e. behavior described [here](https://mtk.sciml.ai/stable/tutorials/ode_modeling/#Defaults-1)). Subsequent `ODEProblem` construction produces a `u0` of mixed (`Any`) eltype and throws exact same error on calls to `solve`.

**Comment by ChrisRackauckas** [comment] 2021-05-18 14:00
Share an example we should test?

**Comment by wsphillips** [comment] 2021-05-18 20:02
I took a look at this more closely and I'm getting the same resulting error but for what's (likely) a different reason. So I'm going to open a separate issue and put the reproducer there.

**Comment by ChrisRackauckas** [comment] 2021-05-19 17:22
Simplified:

```julia
using ModelingToolkit
pars = @parameters(begin
                   x0
                   t
                   end)
vars = @variables(begin
                  x(t)
                  end)
der = Differential(t)
eqs = [der(x) ~ x]
nonLinearSystem = ODESystem(eqs, t, vars, [x0])
pars = [
  x0 => 10.0,
]
initialValues = [
  x => x0
]
problem = ODEProblem(nonLinearSystem, initialValues, tspan, pars)
problem.u0 isa Float64
```

**Comment by ChrisRackauckas** [comment] 2021-05-19 17:22
@pepijndevos can you take a look? This seems like it should be hitting the system you made.

**Comment by pepijndevos** [comment] 2021-05-20 09:16
What's happening is that `process_DEProblem` is called with `x0 => 10.0` in `parammap`.
However, `u0` is constructed with `varmap_to_vars(u0map,dvs; defaults=defs)` while `p` is constructed with `varmap_to_vars(parammap,ps; defaults=defs)`.

For this program to work we would need to merge `parammap` into `defs`, is that desirable?

What currently works:

```julia
using ModelingToolkit
pars = @parameters(begin
                   x0
                   t
                   end)
vars = @variables(begin
                  x(t)
                  end)
der = Differential(t)
eqs = [der(x) ~ x]
pars = [
  x0 => 10.0,
  x => x0
]
sys = ODESystem(eqs, t, vars, [x0], defaults=pars)
tspan = (0.0, 1.0)
problem = ODEProblem(sys, [], tspan)
problem.u0 isa Vector{Float64}
```

**Comment by pepijndevos** [comment] 2021-05-20 09:40
I'm kinda divided between

 * if you want to set an initial condition, why are you passing it as a parameter?
 * defaults for initial conditions and parameters are already merged, why are initial conditions and parameters still separate?
 * seems kinda harmless to just merge `parammap` into `defs` so whatever.

**Comment by ChrisRackauckas** [comment] 2021-05-20 10:21
>defaults for initial conditions and parameters are already merged, why are initial conditions and parameters still separate?

It matches the standard `ODEProblem` form.

>seems kinda harmless to just merge parammap into defs so whatever.

Agreed.

**Closed** 2021-05-20 12:43 UTC
