### ISSUE TITLE
Significant performance regression generating BCR vs DEBio

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#553] opened 2020-08-16 01:07 UTC
```
 ─────────────────────────────────────────────────────────────────────
                              Time                   Allocations      
                      ──────────────────────   ───────────────────────
   Tot / % measured:       9074s / 94.5%           1454GiB / 100%     

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 bODESystem        1    7975s  93.0%   7975s   1425GiB  98.1%  1425GiB
 KenCarp4-1        1     229s  2.67%    229s   9.00GiB  0.62%  9.00GiB
 f1                1     227s  2.65%    227s   10.4GiB  0.72%  10.4GiB
 bODEProb          1     105s  1.22%    105s   6.87GiB  0.47%  6.87GiB
 KenCarp4-2        1    34.4s  0.40%   34.4s    110MiB  0.01%   110MiB
 bionetgen         1    8.01s  0.09%   8.01s    894MiB  0.06%   894MiB
 f2                1    265μs  0.00%   265μs      128B  0.00%     128B
 ─────────────────────────────────────────────────────────────────────[
```

DEBio (see https://github.com/SciML/OrdinaryDiffEq.jl/issues/664)
```
                              Time                   Allocations      
                       ──────────────────────   ───────────────────────
   Tot / % measured:         239s / 100%            4.50GiB / 100%     
 Section       ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────────
 CVODE_BDF-1        1    62.3s  26.1%   62.3s    155MiB  3.36%   155MiB
 CVODE_BDF-2        1    61.0s  25.5%   61.0s   92.1MiB  2.00%  92.1MiB
 f1                 1    41.6s  17.4%   41.6s   3.42GiB  75.9%  3.42GiB
 KenCarp4-1         1    34.7s  14.5%   34.7s    427MiB  9.26%   427MiB
 KenCarp4-2         1    32.3s  13.5%   32.3s   69.3MiB  1.50%  69.3MiB
 addodes            1    5.83s  2.44%   5.83s    231MiB  5.01%   231MiB
 netgen             1    1.21s  0.51%   1.21s    135MiB  2.92%   135MiB
 ODEProb            1   10.8ms  0.00%  10.8ms   1.86MiB  0.04%  1.86MiB
 f2                 1   79.4μs  0.00%  79.4μs     32.0B  0.00%    32.0B
 ──────────────────────────────────────────────────────────────────────

```

Solution looks qualitatively the same as the Bionetgen solution. Agreement with Bionetgen is still not great quantitatively though (less than two decimal places of agreement for ~ 5% of the variables), but I think that was always the case. I can check what DEBio gives to make sure we are getting similar solutions with it.

**Comment by ChrisRackauckas** [comment] 2020-08-16 01:20
This is https://github.com/SciML/ModelingToolkit.jl/issues/551 . Remember we had a hack in DEBio to stop it, and we just need to add that to `build_function`.

**Comment by isaacsas** [comment] 2020-08-16 01:27
Everything is significantly slower, but the worst is the conversion to the ODESystem. However, that doesn't involve calling `build_function` does it? Isn't that in the `ODEProblem` call?

**Comment by ChrisRackauckas** [comment] 2020-08-16 01:30
Oh yes, I was talking about the solve part which is definitely the `+(a,b,c,d,e,f,g,...)` issue. That ODESystem generation time is ridiculous though and worth looking into. How was that done?

**Comment by isaacsas** [comment] 2020-08-16 01:32
This should be the core of the conversion in the `ReactionSystem`:

https://github.com/SciML/ModelingToolkit.jl/blob/3454522e5062215f6f4b30232d0b27fe83168372/src/systems/reaction/reactionsystem.jl#L189

The rest would be the `ODESystem` constructor which also seems to have a fair amount that it does.

**Comment by ChrisRackauckas** [comment] 2020-08-16 01:35
incrementally adding might be a bad idea. I wonder if it's better to try and do a `reduce(+,...)` specialization

**Comment by isaacsas** [comment] 2020-08-16 01:38
Could the `iszero` also be a potential issue? I vaguely recall that got *a lot* slower at some point and I had to add a flag in DiffEqJump to allow MT to disable using it.

**Comment by ChrisRackauckas** [comment] 2020-08-16 01:39
I thought @shashi  added somethin so that it wouldn't call simplify when it didn't need to.

**Comment by isaacsas** [comment] 2020-08-16 01:43
Could be -- it was a couple months ago that I was dealing with that during the jump conversion optimization...

**Comment by shashi** [comment] 2020-09-14 15:26
`iszero` simplifies by default. I recommend writing something like [`_iszero`](https://github.com/SciML/ModelingToolkit.jl/blob/945af7f1040770d1eeaa410d27f2bf531856ccb6/src/differentials.jl#L135-L138) If you know it's going to be either a constant 0 or an un-simplifiable expression.

Do try with #581 to see if your this is related to #551

**Comment by isaacsas** [comment] 2020-11-28 03:27
@shashi @YingboMa So on MT 4.0.6 and Catalyst 6.0.0 things are looking much much much better! Seems like the conversion of a `ReactionSystem` to `ODESystem` issue is fixed. This was the previous overwhelming rate limiting step, and is where the MT (symbolic) ODEs are generated. We aren't quite reaching the performance we saw under DEBio though yet. The big remaining issues seem to be that 
1. KenCarp4-1 shows a big slowdown on the first run that was not present with DEBio, and is still about 30% slower after compilation. But perhaps this is due to changes in Julia, compilers or OS since the DEBio benchmark was run. Or, perhaps this is due to 3. below.
2. `ODEProblem` on the converted `ODESystem` is currently near rate limiting. 
3. ODE rhs function evaluation after compilation is about a factor of two slower than DEBio was giving.

Here is the latest table (benchmarks are all on my laptop, which is what I used above, but Julia versions and/or Mac OS versions could have changed). This is from running the script https://github.com/isaacsas/ReactionNetworkImporters.jl/blob/master/examples/test_bcr_odes.jl with ReactionNetworkImporters master (should be the same as v.0.3.0):
```
                              Time                   Allocations      
                      ──────────────────────   ───────────────────────
   Tot / % measured:        307s / 100%            33.1GiB / 100%     

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 KenCarp4-1        1     104s  34.1%    104s   6.80GiB  20.6%  6.80GiB
 bODEProb          1     103s  33.8%    103s   21.2GiB  64.3%  21.2GiB
 KenCarp4-2        1    43.8s  14.4%   43.8s    110MiB  0.33%   110MiB
 f1                1    41.6s  13.6%   41.6s   3.53GiB  10.7%  3.53GiB
 bionetgen         1    11.2s  3.67%   11.2s   1.19GiB  3.62%  1.19GiB
 bODESystem        1    1.50s  0.49%   1.50s    154MiB  0.46%   154MiB
 f2                1    154μs  0.00%   154μs      192B  0.00%     192B
 ─────────────────────────────────────────────────────────────────────175.67009447635792
```

**Comment by shashi** [comment] 2020-12-08 16:46
@isaacsas how do I get the data to go with the script?

**Comment by shashi** [comment] 2020-12-08 16:46
Ah I see it's in the repo

**Comment by isaacsas** [comment] 2020-12-08 17:00
Feel free to hit me up on Slack if you are working on it and have any issues too!

**Comment by isaacsas** [comment] 2021-01-02 18:07
Working on updating the BCR benchmark, so reran for current values. As of 1/2/21 the compiled ODE rhs seems to have the same performance as we were previously seeing with DEBio (KenCarp4 is still a bit slower for some reason, but perhaps something changed in the ODE solver...). The big rate limiting step is still generation of the ODEProblem from the ODESystem:
```
─────────────────────────────────────────────────────────────────────
                              Time                   Allocations      
                      ──────────────────────   ───────────────────────
   Tot / % measured:        230s / 99.5%           23.5GiB / 100%     

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 KenCarp4-1        1    86.1s  37.6%   86.1s   6.68GiB  28.6%  6.68GiB
 bODEProb          1    56.6s  24.7%   56.6s   11.9GiB  50.8%  11.9GiB
 KenCarp4-2        1    40.1s  17.5%   40.1s    110MiB  0.46%   110MiB
 f1                1    35.4s  15.5%   35.4s   3.53GiB  15.1%  3.53GiB
 bionetgen         1    9.55s  4.17%   9.55s   1.06GiB  4.53%  1.06GiB
 bODESystem        1    1.37s  0.60%   1.37s    138MiB  0.58%   138MiB
 f2                1   79.3μs  0.00%  79.3μs      192B  0.00%     192B
 ─────────────────────────────────────────────────────────────────────
```

**Comment by isaacsas** [comment] 2021-03-04 15:36
@shashi @ChrisRackauckas seems like `build_function` is generating much less efficient compiled functions? I'm now getting for BCR
```
───────────────────────────────────────────────────────────────────
                            Time                   Allocations      
                    ──────────────────────   ───────────────────────
  Tot / % measured:       103s / 99.2%           8.62GiB / 99.4%    

 Section    ncalls     time   %tot     avg     alloc   %tot      avg
 ───────────────────────────────────────────────────────────────────
 f1              1    55.2s  54.2%   55.2s   2.38GiB  27.9%  2.38GiB
 bODEProb        1    34.5s  33.9%   34.5s   4.63GiB  54.1%  4.63GiB
 bionetgen       1    8.13s  7.99%   8.13s    853MiB  9.73%   853MiB
 bODESystem      1    3.95s  3.88%   3.95s    728MiB  8.31%   728MiB
 f2              1   1.41ms  0.00%  1.41ms    892KiB  0.01%   892KiB
 ───────────────────────────────────────────────────────────────────
```

Notice the second call to the compiled BCR ODE derivative, `f2`, is ~1.5ms vs .08ms previously. I had planned to show this off for my talk tomorrow, but I think I'll hold off for now since there seem to be issues again. (In contrast, compared to the last time I benchmarked in the previous message it looks like ODEProblem construction has gone down by about 20s.)

**Comment by isaacsas** [comment] 2021-03-04 15:37
For reference I'm using:
```
Project ReactionNetworkImporters v0.6.0
Status `~/.julia/dev/ReactionNetworkImporters/Project.toml`
  [479239e8] Catalyst v6.8.1
  [864edb3b] DataStructures v0.18.9
  [961ee093] ModelingToolkit v5.11.0
  [d1185830] SymbolicUtils v0.8.4
  [2f01184e] SparseArrays
```

**Comment by isaacsas** [comment] 2021-03-04 15:38
Also notice, the memory allocations in the second call to the ODE derivative function are much bigger now.

**Comment by ChrisRackauckas** [comment] 2021-03-04 16:27
@shashi it would be good to figure out what's allocating there. It should be 0 or 32.0B (i.e. returning a scalar). This is doing something really bad.

**Comment by isaacsas** [comment] 2021-03-04 22:38
@shashi I tried the PR and get these timings now, so better, but still seems somewhat slower (80μs before vs ~130μs now):
```
 ─────────────────────────────────────────────────────────────────────
                              Time                   Allocations      
                      ──────────────────────   ───────────────────────
   Tot / % measured:        125s / 86.7%           9.91GiB / 98.0%    

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 f1                1    60.5s  55.7%   60.5s   2.89GiB  29.7%  2.89GiB
 bODEProb          1    37.5s  34.5%   37.5s   5.55GiB  57.1%  5.55GiB
 bionetgen         1    6.22s  5.73%   6.22s    588MiB  5.91%   588MiB
 bODESystem        1    4.36s  4.01%   4.36s    725MiB  7.29%   725MiB
 f2                2    264μs  0.00%   132μs      224B  0.00%     112B
 ─────────────────────────────────────────────────────────────────────
```

**Comment by ChrisRackauckas** [comment] 2021-03-11 09:12
@shashi was the issue here figured out?

**Comment by isaacsas** [comment] 2021-03-11 12:52
Still not quite matching the performance from prior to the rewrite 132μs vs 81.4μs previously.

**Comment by shashi** [comment] 2021-03-13 19:59
Here is what I got from running http://codepad.org/lQF9i8pu on v0.4.5 and master

 v0.4.5

```julia
 ────────────────────────────────────────────────────────────────────
                             Time                   Allocations
                     ──────────────────────   ───────────────────────
  Tot / % measured:       47.3s / 98.4%           12.1GiB / 99.5%

 Section     ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────
 ODEProb ...      1    38.5s  82.7%   38.5s   10.8GiB  89.8%  10.8GiB
 Parse Ne...      1    6.95s  14.9%   6.95s   1.04GiB  8.68%  1.04GiB
 Create O...      1    1.10s  2.36%   1.10s    188MiB  1.53%   188MiB
 ──────────────────────────────────────────────────────────────────── ────────────────────────────────────────────────────────────────────
                             Time                   Allocations
                     ──────────────────────   ───────────────────────
  Tot / % measured:       47.5s / 97.8%           12.1GiB / 99.4%

 Section     ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────
 ODEProb ...      1    38.5s  82.7%   38.5s   10.8GiB  89.8%  10.8GiB
 Parse Ne...      1    6.95s  14.9%   6.95s   1.04GiB  8.68%  1.04GiB
 Create O...      1    1.10s  2.36%   1.10s    188MiB  1.53%   188MiB
 ──────────────────────────────────────────────────────────────────── ────────────────────────────────────────────────────────────────────
                             Time                   Allocations
                     ──────────────────────   ───────────────────────
  Tot / % measured:       78.3s / 98.7%           15.5GiB / 99.5%

 Section     ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────
 ODEProb ...      1    38.5s  49.8%   38.5s   10.8GiB  70.0%  10.8GiB
 ODERHS E...      1    30.8s  39.8%   30.8s   3.39GiB  22.1%  3.39GiB
 Parse Ne...      1    6.95s  8.99%   6.95s   1.04GiB  6.77%  1.04GiB
 Create O...      1    1.10s  1.42%   1.10s    188MiB  1.20%   188MiB
 ODERHS E...      1   74.4μs  0.00%  74.4μs      192B  0.00%     192B

```
master
```
 ─────────────────────────────────────────────────────────────────────
                              Time                   Allocations
                      ──────────────────────   ───────────────────────
   Tot / % measured:       15.9s / 100%            4.32GiB / 100%

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 ODEProb N...      1    14.2s  89.2%   14.2s   3.68GiB  85.0%  3.68GiB
 Create OD...      1    928ms  5.85%   928ms    513MiB  11.6%   513MiB
 Parse Net...      1    784ms  4.94%   784ms    149MiB  3.38%   149MiB
 ───────────────────────────────────────────────────────────────────── ─────────────────────────────────────────────────────────────────────
                              Time                   Allocations
                      ──────────────────────   ───────────────────────
   Tot / % measured:       15.9s / 100%            4.32GiB / 100%

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 ODEProb N...      1    14.2s  89.2%   14.2s   3.68GiB  85.0%  3.68GiB
 Create OD...      1    928ms  5.85%   928ms    513MiB  11.6%   513MiB
 Parse Net...      1    784ms  4.94%   784ms    149MiB  3.38%   149MiB
 ─────────────────────────────────────────────────────────────────────
 ─────────────────────────────────────────────────────────────────────
                              Time                   Allocations
                      ──────────────────────   ───────────────────────
   Tot / % measured:       93.5s / 100%            7.57GiB / 100%

 Section      ncalls     time   %tot     avg     alloc   %tot      avg
 ─────────────────────────────────────────────────────────────────────
 ODERHS Eval1      1    77.6s  83.0%   77.6s   3.25GiB  42.9%  3.25GiB
 ODEProb N...      1    14.2s  15.2%   14.2s   3.68GiB  48.6%  3.68GiB
 Create OD...      1    928ms  0.99%   928ms    513MiB  6.61%   513MiB
 Parse Net...      1    784ms  0.84%   784ms    149MiB  1.93%   149MiB
 ODERHS Eval2      1   55.2μs  0.00%  55.2μs      464B  0.00%     464B
 ─────────────────────────────────────────────────────────────────────
```


Also,

v4.5.0
```
julia> @btime $(oprob.f.f.f_iip)($du,$u,$p,0.)
  34.029 μs (0 allocations: 0 bytes)
```
v5.6.0 (the last version without the build_function rewrite)
For a brief period when we introduced `Add` `Mul` our unflatten_long_ops was silently broken:
```julia
julia> @btime $(oprob.f.f.f_iip)($du,$u,$p,0.)
  985.774 μs (37646 allocations: 891.94 KiB)
```

This was awful.

But on the latest release:
```
julia> @btime $(oprob.f.f.f_iip)($du,$u,$p,0.)
  15.770 μs (0 allocations: 0 bytes)
```

I am going to close this issue, it has become pretty useless. In the future, please open one issue per problem with the reproducer in the OP. This should have been at least 3 issues I feel. And always use `@btime` when not timing compilation because `@timeit` will lie to you!!

**Closed by shashi** 2021-03-13 19:59 UTC
Labels: bug, performance
