### ISSUE TITLE
build_function errors with type Int64 has no field value

### ISSUE THREAD

**Issue by michakraus** [SciML/ModelingToolkit.jl#659] opened 2020-11-20 10:00 UTC
The simple example
```julia
@variables x
@derivatives Dx'~x
build_function(expand_derivatives(Dx(1 / exp(x))),x)
```
yields
```
type Int64 has no field value
```
I am using ModelingToolkit v4.0.5 on Julia v1.5.3.

**Comment by ChrisRackauckas** [comment] 2020-11-20 13:59
This is a duplicate of https://github.com/SciML/ModelingToolkit.jl/issues/654 . It should be fixed on master with https://github.com/SciML/ModelingToolkit.jl/pull/656 . Could you try running master?

**Comment by ChrisRackauckas** [comment] 2020-11-20 14:05
Actually I just checked: https://github.com/SciML/ModelingToolkit.jl/pull/656 fixed this case on master, so we'll make sure to release a patch.

**Closed by ChrisRackauckas** 2020-11-20 14:05 UTC
